version: '3.3'
services:
  wildfly:
    build:
     context: configs
     dockerfile: Dockerfile
    image: sofislab/wildfly:15-jdk11
    volumes:
      - $PWD/wildfly15:/opt/wildfly15
    env_file:
      - Config.env
    ports:
     - "8081:8080"
    networks:
     - integracion

networks:
  integracion:
      driver: bridge
      ipam:
        driver: default
        config:
         - subnet: 142.18.0.0/16
